### ISSUE TITLE
Can you please update this repo with routing for web(compose DOM) as well?

### ISSUE THREAD

**Issue by sdzshn3** [arkivanov/ComposeNavigatorExample#1]

**Comment by arkivanov** [comment]
Compose for Web is still highly experimental. The DOM variant would also require re-implementing the UI from scratch. Also Decompose doesn't support Compose for Web (DOM), but it does support JavaScript in general and also Compose for Web (Canvas).

Please refer to the following sample: [JetBrains TodoApp sample for Compose for Web (DOM)](https://github.com/JetBrains/compose-multiplatform/tree/master/examples/todoapp/web). It demonstrate the usage of Decompose with Compose for Web.

Thanks!
