### ISSUE TITLE
How to import libs like .toml file, but without him?:)

### ISSUE THREAD

**Issue by arstagaev** [arkivanov/ComposeNavigatorExample#2]
https://github.com/arkivanov/ComposeNavigatorExample/blob/d786d92632fe22e4d7874645ba2071fb813f9ace/android/build.gradle#L31

**Comment by arkivanov** [comment]
Sorry, I don't get the question. Could you elaborate?

**Comment by arstagaev** [comment]
Thank you for answer! How to get information about library version of this import? E.g. `compose.runtime`

**Comment by arkivanov** [comment]
The version of the Compose dependencies usually the same as the version of the Compose Gradle pluging (`org.jetbrains.compose`). It's defined here: https://github.com/arkivanov/ComposeNavigatorExample/blob/d786d92632fe22e4d7874645ba2071fb813f9ace/build.gradle#L14

**Comment by arstagaev** [comment]
Understood, thanks!
